baseURL = "https://hafzan-technologies.github.io/blog2/"
languageCode = "en-us"
title = "Chronicles of Amaanullah"
rssLimit = 20
copyright = "2021 Amaanullah Bhatti All rights reserved"
minify = false

[Author]
  name = "Amaanullah Bhatti"
  email = "me@example.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]
